// <auto-generated />
using System;
using GEST.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GEST.Infrastructure.Migrations
{
    [DbContext(typeof(GestDbContext))]
    [Migration("20251109032954_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GEST.Domain.Entities.ParkingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AppliedPricePerHour")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("EntryTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExitTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ParkedTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PricingTier")
                        .HasColumnType("int");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int");

                    b.Property<int?>("SpotId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_ParkingSession");

                    b.HasIndex("SpotId");

                    b.HasIndex("SectorId", "ExitTimeUtc")
                        .HasDatabaseName("IX_Session_BySector_ExitTime");

                    b.HasIndex("VehicleId", "Status")
                        .HasDatabaseName("IX_Session_ByVehicle_Status");

                    b.ToTable("ParkingSessions", (string)null);
                });

            modelBuilder.Entity("GEST.Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Sector");

                    b.ToTable("Sectors", (string)null);
                });

            modelBuilder.Entity("GEST.Domain.Entities.Spot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentLicensePlate")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Spot");

                    b.HasIndex("SectorId")
                        .HasDatabaseName("IX_Spot_BySector");

                    b.HasIndex("SectorId", "IsOccupied")
                        .HasDatabaseName("IX_Spot_BySector_IsOccupied");

                    b.ToTable("Spots", (string)null);
                });

            modelBuilder.Entity("GEST.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id")
                        .HasName("PK_Vehicle");

                    b.HasIndex("LicensePlate")
                        .IsUnique()
                        .HasDatabaseName("IX_Vehicle_ByLicensePlate");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("GEST.Domain.Entities.WebhookEventLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("EntryTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExitTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Lat")
                        .HasColumnType("float");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<double?>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate", "ReceivedAtUtc")
                        .HasDatabaseName("IX_WebhookEventLog_ByLicensePlate_ReceivedAt");

                    b.ToTable("WebhookEventLogs", (string)null);
                });

            modelBuilder.Entity("GEST.Domain.Entities.ParkingSession", b =>
                {
                    b.HasOne("GEST.Domain.Entities.Sector", "Sector")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Sector_ParkingSession");

                    b.HasOne("GEST.Domain.Entities.Spot", "Spot")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Spot_ParkingSession");

                    b.HasOne("GEST.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Vehicle_ParkingSession");

                    b.Navigation("Sector");

                    b.Navigation("Spot");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GEST.Domain.Entities.Spot", b =>
                {
                    b.HasOne("GEST.Domain.Entities.Sector", "Sector")
                        .WithMany("Spots")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Sector_Spot");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("GEST.Domain.Entities.Sector", b =>
                {
                    b.Navigation("ParkingSessions");

                    b.Navigation("Spots");
                });

            modelBuilder.Entity("GEST.Domain.Entities.Spot", b =>
                {
                    b.Navigation("ParkingSessions");
                });

            modelBuilder.Entity("GEST.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("ParkingSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
