// <auto-generated />
using System;
using GEST.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GEST.Infrastructure.Migrations
{
    [DbContext(typeof(GestDbContext))]
    partial class GestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GEST.Domain.Entities.ParkingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AppliedPricePerHour")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("EntryTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExitTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime?>("ParkedTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PricingTier")
                        .HasColumnType("int");

                    b.Property<string>("SectorCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("SpotId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("SpotId");

                    b.HasIndex("LicensePlate", "Status")
                        .HasDatabaseName("IX_Session_ActiveByPlate");

                    b.HasIndex("SectorCode", "ExitTimeUtc");

                    b.ToTable("ParkingSessions", (string)null);
                });

            modelBuilder.Entity("GEST.Domain.Entities.Sector", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("Sectors", (string)null);
                });

            modelBuilder.Entity("GEST.Domain.Entities.Spot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentLicensePlate")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SectorCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("SectorCode");

                    b.HasIndex("SectorCode", "IsOccupied");

                    b.ToTable("Spots", (string)null);
                });

            modelBuilder.Entity("GEST.Domain.Entities.Vehicle", b =>
                {
                    b.Property<string>("LicensePlate")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("LicensePlate");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("GEST.Domain.Entities.WebhookEventLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("EntryTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExitTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Lat")
                        .HasColumnType("float");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<double?>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate", "ReceivedAtUtc");

                    b.ToTable("WebhookEventLogs", (string)null);
                });

            modelBuilder.Entity("GEST.Domain.Entities.ParkingSession", b =>
                {
                    b.HasOne("GEST.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("LicensePlate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GEST.Domain.Entities.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GEST.Domain.Entities.Spot", "Spot")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sector");

                    b.Navigation("Spot");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GEST.Domain.Entities.Spot", b =>
                {
                    b.HasOne("GEST.Domain.Entities.Sector", "Sector")
                        .WithMany("Spots")
                        .HasForeignKey("SectorCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("GEST.Domain.Entities.Sector", b =>
                {
                    b.Navigation("Spots");
                });

            modelBuilder.Entity("GEST.Domain.Entities.Spot", b =>
                {
                    b.Navigation("ParkingSessions");
                });

            modelBuilder.Entity("GEST.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("ParkingSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
